### PR TITLE
Add FP merge/mv instructions

### PR DESCRIPTION
**Pull request by mp-17**
Add the following instructions:
* `vfmerge.vfm`
* `vfmv.v.f`

**Notes**:
(Deprecated) A private merge-unit was added to the `vmfpu` FU since the NaN-box check is mandatory for the immediate of these instructions.
These instructions are now handled by the VALU.

### CODE REVIEW

**Comment by mp-17** [comment]
`vfmerge` and `vfmv` are now handled by the `VALU`, to remove timing pressure from the FPU. For this reason, the NaN-box check was moved from the `vmfpu` to the dispatcher.

**Comment by suehtamacv** [comment]
Thanks for your contribution, @mp-17, this MR looks good to me. Can you rebase on top of main, and update the `FUNCTIONALITIES` file? I can merge it once the CI passes.

**Review by suehtamacv — CHANGES_REQUESTED** [review]
Thanks for your contribution, @mp-17, this MR looks good to me. Can you rebase on top of main, and update the FUNCTIONALITIES file? I can merge it once the CI passes.

**Comment by mp-17** [comment]
Done, let's wait for the CI

**Review by suehtamacv — APPROVED** [review]
LGTM. I will merge it once the CI passes.

**Pull request merged**
