### PR TITLE
[HW] Floating-Point classify, division, sqrt

### PR DESCRIPTION
**Pull request by mp-17**
# This PR depends on https://github.com/pulp-platform/ara/pull/133, https://github.com/pulp-platform/ara/pull/142.

Add floating-point classify, division, sqrt instructions, delayed because of the FPU.
I updated the CVA6 submodule, which now points to the modified FPU, able to classify as expected. 
Moreover, the bug related to the synchronization of the FPU lanes is now solved.

### Added

- Vector floating-point classify instruction (`vfclass`)
- Vector floating-point divide instructions (`vfdiv`, `vfrdiv`) 
- Vector floating-point square-root instruction (`vfsqrt`)

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed
- [x] No frequency degradation

### CODE REVIEW

**Comment by mp-17** [comment]
Ready for review when the automated tests pass! ;-)

**Comment by suehtamacv** [comment]
Delaying the merge until the backend issues with the divider are solved.

**Comment by suehtamacv** [comment]
Any chance we can replace FPNew's divider with the new divider everyone is talking about? ;)

**Comment by mp-17** [comment]
> Any chance we can replace FPNew's divider with the new divider everyone is talking about? smirk

Indeed, it's in the pipeline! ;-)

**Comment by mp-17** [comment]
> Any chance we can replace FPNew's divider with the new divider everyone is talking about? smirk

Unluckily, it is 32-bits only :-/

**Comment by mp-17** [comment]
Backend problems are solved now, let's merge this as soon as the tests pass ;-)

**Comment by mp-17** [comment]
@suehtamacv, we can merge this now, right?

**Pull request merged**
