### PR TITLE
following lowRISC coding style for sv section parameterized-objects-m…

### PR DESCRIPTION
**Pull request by hossein1387**
localparams should be used were there are module-scoped constant.

### CODE REVIEW

**Review by suehtamacv — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution, @hossein1387! Your changes look good to me. 

Could you please rebase your work on top of `main`, so that we can check that the CI still passes after those changes? Once it passes, I can merge it.

**Comment by suehtamacv** [comment]
I added an issue (#20) for a broad-scope analysis of Ara's compliance with lowRISC coding style guidelines.

**Comment by hossein1387** [comment]
> Thanks a lot for your contribution, @hossein1387! Your changes look good to me.
> 
> Could you please rebase your work on top of `main`, so that we can check that the CI still passes after those changes? Once it passes, I can merge it.

By the way I cannot see any CI checks so I am not sure if the tests have passed or not. Is CI running in private mode?

**Review by suehtamacv — APPROVED** [review]
I understand what is happening. The CI only triggers upon a push, not upon a pull request. Because of that, the CI never ran on `pulp-platform/ara`, but on ` hossein1387/ara`. I checked [that](https://github.com/hossein1387/ara/actions/runs/662798487) CI and saw that it passes, so I am approving this PR. I will change the CI behavior with a later PR. 

Thanks for your contribution!

**Pull request merged**
